<?php

use yii\db\Migration;
use MongoDB\Client;

class m241010_103834_create_example_table extends Migration
{
    private $tableName = 'example';

    public function safeUp()
    {
        $mongodb_param = require(\Yii::getAlias('@app/config/mongodb.php'));
        $params = require(\Yii::getAlias('@app/config/params.php'));
        $UTCTimestamp = gmdate($params['timestamp']['UTC']);
        $createdBy = 'testid';
        
        if (!YII_ENV_DEV) {
            echo "Skipping migration/fresh for non-dev environment.\n";
            return true;
        }

        $mongodb = new Client($mongodb_param['dsn']);
        $collection = $mongodb->selectCollection($mongodb_param['database'], $this->tableName);
        $collection->drop();

        $this->createTable('{{%' . $this->tableName . '}}', [
            'id' => $this->integer()->append('PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY'),
            'name' => $this->string(255)->notNull(),
            'status' => $this->smallInteger()->notNull()->defaultValue(2)->comment('0: Inactive, 1: Active, 2: Draft, 3: Completed, 4: Deleted, 5: Maintenance'),
            'detail_info' => $this->json()->notNull()->defaultValue(json_encode([
                'change_log' => [
                    'created_at' => null,
                    'created_by' => null,
                    'deleted_at' => null,
                    'deleted_by' => null,
                    'updated_at' => null,
                    'updated_by' => null,
                ],
            ])),
            'sync' => $this->smallInteger()->defaultValue(null)->comment('1: unsync, null: synced'),
            // 'lock_version' => $this->integer()->notNull()->defaultValue(1)->comment('Optimistic Locking'),
        ]);

        if (!YII_ENV_DEV) {
            echo "Skipping migration/fresh for non-dev environment.\n";
            return true;
        }

        $dummyData = [
            [
                'name' => 'Example',
                'status' => 1,
                'detail_info' => [
                    'change_log' => [
                        'created_at' => $UTCTimestamp,
                        'created_by' => $createdBy,
                        'deleted_at' => null,
                        'deleted_by' => null,
                        'updated_at' => null,
                        'updated_by' => null,
                    ],
                ],
                'sync' => null,
            ],
        ];

        foreach ($dummyData as $key => $value) {
            $this->insert('{{%' . $this->tableName . '}}', $value);
            $insertID['id'] = $key + 1;
            $collection->insertOne($insertID + $value);
        }
    }

    public function safeDown()
    {
        if (!YII_ENV_DEV) {
            echo "Skipping migration/fresh for non-dev environment.\n";
            return true;
        }

        $mongodb_param = require(\Yii::getAlias('@app/config/mongodb.php'));
        
        $mongodb = new Client($mongodb_param['dsn']);
        $collection = $mongodb->selectCollection($mongodb_param['database'], $this->tableName);
        $collection->drop();

        $this->dropTable('{{%' . $this->tableName . '}}');
    }
}
